// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.db;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(Connection))]
    [Migration("20230822044406_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.MenuModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("lft")
                        .HasColumnType("int");

                    b.Property<int?>("parentID")
                        .HasColumnType("int");

                    b.Property<int>("rgt")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("parentID");

                    b.ToTable("menu");
                });

            modelBuilder.Entity("backend.Models.MenuModel", b =>
                {
                    b.HasOne("backend.Models.MenuModel", "parent")
                        .WithMany("childrens")
                        .HasForeignKey("parentID");

                    b.Navigation("parent");
                });

            modelBuilder.Entity("backend.Models.MenuModel", b =>
                {
                    b.Navigation("childrens");
                });
#pragma warning restore 612, 618
        }
    }
}
